import pandas_ta as ta
def preprocess(df: pd.DataFrame) -> pd.DataFrame:
    """
    Calculate a new technical index

    Args:
        df(pd.DataFrame) : ohlcv-styled time bar

    Returns:
        new_df: pd.DataFrame
        With a new technical index column
    """
    new_df = df.copy()
    close = new_df['cl']
    ### Technical indexes ###
    new_df['SMA10'] = ta.sma(close, length=10)
    new_df['RSI'] = ta.rsi(close, length=10)
    return new_df

def preprocess_technicalIndex(df: pd.DataFrame) -> pd.DataFrame:
    """
    Calculate Technical indexes and return with new columns
    Args:
        df(pd.DataFrame): Time Bar(OHLCV)
    Returns:
        pd.DataFrame
    """
    new_df = df.copy()
    openVal, high, low, close, volume = new_df["op"], new_df["hi"], new_df["lo"], new_df["cl"], new_df["volume"]
    ichimoku_visible, _ = ta.ichimoku(high, low, close)
    new_df["ISA_9"] = ichimoku_visible["ISA_9"] /close # spanA
    new_df["ISB_26"] = ichimoku_visible["ISB_26"] /close # spanB
    new_df["ITS_9"] = ichimoku_visible["ITS_9"] /close # Tenkan-Sen
    new_df["IKS_26"] = ichimoku_visible["IKS_26"] /close # Kijun-Sen

    bbands = ta.bbands(close, length=10)
    # Access columns using the precise names generated by pandas-ta
    new_df["BBL_10_2.0"] = bbands.iloc[:, 0] / close
    new_df["BBU_10_2.0"] = bbands.iloc[:, 2] / close

    new_df["ema5"] = ta.ema(close, 5) /close
    new_df["ema10"] = ta.ema(close, 10)/close
    new_df["sma5"] = ta.sma(close, 5)/close
    new_df["sma10"] = ta.sma(close, 10)/close
    new_df["MFI"] = ta.mfi(high, low, close, volume, timeperiod=16)

    new_df["MIDPOINT"] = ta.midpoint(close, timeperiod=16) / close
    new_df["T3"] = ta.t3(close, timeperiod=4, vfactor=0) / close
    new_df["TEMA"] = ta.tema(close, timeperiod=24) / close
    new_df["TRIMA"] = ta.trima(close, timeperiod=24) / close
    new_df["APO"] = ta.apo(close, fastperiod=12, slowperiod=26, matype=0)
    new_df["WILLR"] = ta.willr(high, low, close, timeperiod=16)
    new_df["ATR"] = ta.atr(high, low, close, timeperiod=16)
    new_df["NATR"] = ta.natr(high, low, close, timeperiod=1)

    return new_df.dropna()

def make_tech_idc(time_bar):
    df = time_bar.copy(deep=True)

    # Moving Average Cross determines side
    df["sma_short"] = df["cl"].rolling(window=period_short_sma).mean()
    df["sma_long"] = df["cl"].rolling(window=period_long_sma).mean()

    # Bolinger Bands
    df['bbstd'] = df['cl'].rolling(window=period_short_sma).std()
    df['bbh1'] = df['sma_short'] + df['bbstd'] * 1
    df['bbl1'] = df['sma_short'] - df['bbstd'] * 1
    df['bbh2'] = df['sma_short'] + df['bbstd'] * 2
    df['bbl2'] = df['sma_short'] - df['bbstd'] * 2
    df['bbh3'] = df['sma_short'] + df['bbstd'] * 3
    df['bbl3'] = df['sma_short'] - df['bbstd'] * 3
    df.dropna()

    return df